# Generated by Django 5.0.3 on 2026-03-03 19:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('num_estudiantes', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('coordinador', 'Coordinador'), ('docente', 'Docente')], default='docente', max_length=20)),
                ('horas_contrato', models.FloatField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ModuloAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('tutoria', 'Tutoría'), ('clase', 'Clase'), ('grupo_practica', 'Grupo Práctica'), ('encargatura', 'Encargatura')], max_length=30)),
                ('unidad', models.CharField(choices=[('periodos', 'Períodos'), ('grupos', 'Grupos')], default='grupos', max_length=20)),
                ('factor_d', models.FloatField(help_text='Horas directas por unidad')),
                ('factor_i', models.FloatField(default=0, help_text='Horas indirectas por unidad')),
                ('descripcion', models.TextField(blank=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='api.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('anio', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='OtraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('horas', models.FloatField()),
                ('tiene_resolucion', models.BooleanField(default=False)),
                ('tiene_respaldo', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otras_actividades', to=settings.AUTH_USER_MODEL)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otras_actividades', to='api.planificacion')),
            ],
        ),
        migrations.CreateModel(
            name='CargaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0, help_text='Número de períodos o grupos')),
                ('observaciones', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduloasignatura')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='api.planificacion')),
            ],
            options={
                'unique_together': {('planificacion', 'docente', 'modulo')},
            },
        ),
    ]
